version: "3"
services:
  gel:
    image: geldata/gel:6.2
    environment:
      GEL_SERVER_SECURITY: strict
      GEL_SERVER_ADMIN_UI: enabled
      GEL_SERVER_BACKEND_DSN: ${GEL_SERVER_BACKEND_DSN}
      GEL_SERVER_PASSWORD: ${GEL_SERVER_PASSWORD}
      GEL_SERVER_USER: ${GEL_SERVER_USER}
      GEL_SERVER_INSTANCE_NAME: ${GEL_SERVER_INSTANCE_NAME}
      GEL_SERVER_TLS_CERT_MODE: require_file
      GEL_SERVER_TLS_CERT_FILE: ./sutra-tls-cert.crt
      GEL_SERVER_TLS_KEY_FILE: ./sutra-tls-key.key
      GEL_DOCKER_LOG_LEVEL: debug
    volumes:
      - "./dbschema:/dbschema"
      - "./sutra-tls-cert.cert:/sutra-tls-cert.cert"
      - "./sutra-tls-key.key:/sutra-tls-key.key"
    ports:
      - "5656:5656"
      - "10701:10701"
